apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.appPort.db }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: frontend-backend
spec:
  selector:
    app: frontend-backend
  ports:
    - name: front
      protocol: TCP
      port: {{ .Values.appPort.frontend }}
    - name: back
      protocol: TCP
      port: {{ .Values.appPort.backend }}
