apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.image3.repository }}:{{ .Values.image3.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.appPort.db }}
        volumeMounts:
          - name: {{ .Values.volumeMountsDb.name }}
            mountPath: {{ .Values.volumeMountsDb.mountPath }}
        env:
          {{- toYaml .Values.envdb | nindent 10 }}
      volumes:
        - name: {{ .Values.volumeMountsDb.name }} 
