---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-backend
  labels:
    app: frontend-backend
spec:
  selector:
    matchLabels:
      app: frontend-backend
  template:
    metadata:
      labels:
        app: frontend-backend
    spec:
      containers:
      - image: jekisv/frontend
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 80
        env:
          - name: BASE_URL
            value: http://localhost:9000
      - image: jekisv/backend
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 9000
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres:5432/news

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-backend
spec:
  selector:
    app: frontend-backend
  ports:
    - name: front
      protocol: TCP
      port: 80
    - name: back
      protocol: TCP
      port: 9000
